version: "3.7"

services:

  postgres:
    build: './database'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    restart: always

  nats:
    image: "nats-streaming:0.9.2"
    restart: always
    
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.12.2"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # Set minimum and maximum heap size to 1 GB
      - "xpack.security.enabled=false"  # Disable X-Pack security (for development purposes only)
    mem_limit: 2g  # Limit memory usage to 2 GB
    cpu_shares: 512  # Allocate 50% of CPU resources

  feed:
    build: "."
    command: "feed-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: "nats:4222"

  query:
    build: "."
    command: "query-service"
    depends_on:
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"

  pusher:
    build: "."
    command: "pusher-service"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"

  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - "feed"
      - "query"
      - "pusher"